### ISSUE TITLE
Show advanced options does nothing

### ISSUE THREAD

**Issue by atomotic** [DIYBookScanner/spreads#149]
i've just updated spreadpi `Version 0.5git20141106.1250`

when creating a workflow, the **Show advanced options** does nothing, i'm not able to inspect any error or activity inside the browser console.

maybe is something changed in the default config.yaml ?

	driver: chdkcamera
	plugins:
	    - hidtrigger
	    - web
	core:
	    verbose: yes
	    logfile: /home/spreads/.config/spreads/spreads.log
	    capture_keys: [' ', b]
	    loglevel: debug
	device:
	    flip_target_pages: no
	    parallel_capture: yes
	    chdkptp_path: /usr/lib/chdkptp
	    focus_distance: 0
	web:
	    project_dir: /home/spreads/scans
	    debug: no
	    standalone_device: yes
	    mode: scanner
	    port: 5000

**Comment by boredland** [comment]
Doesn't show any options for me:
http://awesomescreenshot.com/08946e9nf0

**Comment by jbaiter** [comment]
Is this still an issue? I made some tests with the latest image/nightly code and didn't notice any problems, neither in the preferences nor the per-workflow configuration.

**Comment by atomotic** [comment]
sorry i forgot to close this ticket
using now `0.5git20150328.c525` everything is fine
thanks
