### ISSUE TITLE
Recent change breaks Python 2.7 support

### ISSUE THREAD

**Issue by gareth8118** [DIYBookScanner/spreads#154]
Commit c5a0cca03c8cf778aaba50c320e4b5f4544f37d3 introduced the following import to plugin.py:

```python
from enum import Enum
```

According to https://docs.python.org/3/library/enum.html, this was introduced in Python 3.4. However, doc/setup-other.rst still claims Python2.7 is sufficient:

    Prerequisites
    -------------
    * Python 2.7 with a recent version of pip_ installed

We either need to bump the minimum supported Python version to 3.4 or find another method of supporting that enumeration.

**Comment by jbaiter** [comment]
There is a backport for 2.7 that is used, it is already declared in setup.py:

     install_requires=[
    "colorama >= 0.2.4",
    "PyYAML >= 3.10",
    "futures >= 2.1",
    "blinker >= 1.3",
    "roman >= 2.0.0",
    "psutil >= 2.0.0",
    "isbnlib >= 3.3.8",
    "enum34 >= 1.0.3",
    ],

https://github.com/DIYBookScanner/spreads/blob/master/setup.py#L152

So simply installing spreads via 'pip' as recommeded by the docs should be enough to take care of the dependency.

**Comment by gareth8118** [comment]
Hi @jbaiter,

OK, the step I was missing when the new dependency was added was to re-install spreads to my virtualenv to get it picked up (line from docs/developers.rst):

    pip install -e ../spreads

Thanks for the quick response.
