### ISSUE TITLE
Configuration empty

### ISSUE THREAD

**Issue by Cypris201** [DIYBookScanner/spreads#160]
In my Spreadpi installation the configuration tab looks like this.

"Show advanced options" dows not work and "Core Device Web" are empty.
Is it a known problem?

(I'm using the spreadpi-20150115 build)

![spreadpi_preferences](https://cloud.githubusercontent.com/assets/6613711/5892145/44480a1a-a4b5-11e4-96d4-e5ee553ff609.jpg)

**Comment by jbaiter** [comment]
Can reproduce, will investigate later this week. Thanks for filing the bug :)

**Comment by jbaiter** [comment]
This was an error on the buildbot, the source was using a newer version of underscore and the buildbot still had the old version cached.
I just forced a new build on the buildbot, so please grab the latest nightly build and try again :-)

**Comment by Cypris201** [comment]
Great, now it works. Thank you.
