### ISSUE TITLE
Intervaltrigger in web not working

### ISSUE THREAD

**Issue by knjigor** [DIYBookScanner/spreads#161]
Hi,
I have a quick question, I have activated Intervaltrigger plugin today and tested it in wizard mode and it is working as it should, but in web mode it isn't working, or I don't know how to activate it.

**Comment by jbaiter** [comment]
Should be fixed now. You either have to recreate your workflow, though or edit the `config.yml` and add `intervaltrigger` to the plugin list there, like this:

    plugins: [intervaltrigger]

**Comment by knjigor** [comment]
```
```

**Comment by jbaiter** [comment]
Did you edit the workflow's configuration file? Does it not work for newly created workflows in the web interface either?

**Comment by knjigor** [comment]
Sorry, I have founded problem, it was:
```
ConfigTypeError: Intervaltrigger.interval must be of type float, not int
```
I added ```.00``` in config.yaml

```
```

**Comment by knjigor** [comment]
One more question, is there a way to pause interval trigger or we have to use finish command <F> key to stop shutting sequence?

**Comment by jbaiter** [comment]
You have to use the finish command key to stop the sequence, currently there's no way to pause, although you could always add that, if you need it, shouldn't be too hard.

**Comment by knjigor** [comment]
Ok, thanx, work perfect, will try to add pause button.

**Comment by knjigor** [comment]
Just one more thing, do I have to add ```plugins: [intervaltrigger]``` every time I create new workflow, it seems that it doesn't add   ```plugins: [intervaltrigger]``` to newly created ones.
