### ISSUE TITLE
Missing dependency for driver 'chdkcamera': chdkptp

### ISSUE THREAD

**Issue by knjigor** [DIYBookScanner/spreads#162]
Hi,
I have done a clean installation of Ubuntu 14.04.1 and followed this installation guide https://github.com/OliPelz/spreads-ubuntu-trusty to install Spreasd (same as last fiew times). After compleating installation I can`t run spreads with chdkcamera driver, i get this message:

``
(.spreads)bsu@bsu:~$ spread configure
Please select a device driver from the following list:
  [0]: Keep current (None)
  [1]: gphoto2camera
  [2]: chdkcamera
  [3]: dummy
  [4]: None
Select a driver: 2
Selected "chdkcamera" as device driver
spreads encountered an error:
Traceback (most recent call last):
  File "/home/bsu/.spreads/local/lib/python2.7/site-packages/spreads/main.py", line 318, in main
    run()
  File "/home/bsu/.spreads/local/lib/python2.7/site-packages/spreads/main.py", line 308, in run
    args.subcommand(config)
  File "/home/bsu/.spreads/local/lib/python2.7/site-packages/spreads/cli.py", line 203, in configure
    driver = plugin.get_driver(config["driver"].get())
  File "/home/bsu/.spreads/local/lib/python2.7/site-packages/spreads/plugin.py", line 457, in get_driver
    .format(driver_name, err.message[16:]), driver_name)
ExtensionException: Missing dependency for driver 'chdkcamera': chdkptp
``
I have tried two times to do a clean installation of Lubuntu and installing Spreads, first time with update of Lubuntu and second without, without luck to start Spreads.

**Comment by jbaiter** [comment]
You have to install chdkptp.py and Lupa before you run the application:

```
$ sudo apt-get install liblua5.2-dev
$ pip install --install-option='--no-luajit' lupa
$ pip install chdkptp.py
```

Will update the documentation soon, haven't gotten around to it yet.

**Comment by knjigor** [comment]
Of course I understand, It is working now, and as I can see it it working much faster then prev. version.

Thanx again.

**Comment by knjigor** [comment]
Spreads is working for me now, but I get some time an error:

spreads.plugin: Finding devices for driver "CHDKCameraDevice"
open_camera_dev_usb: ptp_opensession failed 0x2ff
open_camera_dev_usb:usb_ptp_device_reset(): Device or resource busy
usb_ptp_get_device_status(): Device or resource busy
open_camera_dev_usb: ptp_opensession failed 0x2ff
open_camera_dev_usb:usb_ptp_device_reset(): Device or resource busy
usb_ptp_get_device_status(): Device or resource busy
Cameras are working and taking pictures, but this error keeps raising, sometime at starting web some time at capturing sequence.

**Comment by jbaiter** [comment]
This happens when for some reason the driver loses connection to the camera, it will then try to re-connect up to two times, these are the messages from that from the low-level USB code.
Does this break the workflow in your case? Do you have to restart the cameras manually?

**Comment by knjigor** [comment]
No, as you said it tries to connect to cameras and finally reconnect (some time it lose connection to to left some time to right one), and it continue to work, what I did notice is that at point of connecting and reconnecting pictures aren't cropped. In very rare cases I have to stop spreads and restart it, maybe once or twice in 900 pages.
