### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by markvdb** [DIYBookScanner/spreads#165]
Using Version 0.5git20150206.1a43 from a fresh 20150206 spreadpi buildbot image, I start by creating a workflow. I get to the capture screen and I get stuff like this in the logs:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/spreadsplug/web/endpoints.py", line 522, in list_workflows
    workflows = Workflow.find_all(app.config['base_path'])
  File "/usr/local/lib/python2.7/dist-packages/spreads/workflow.py", line 355, in find_all
    workflow = cls(candidate)
  File "/usr/local/lib/python2.7/dist-packages/spreads/workflow.py", line 426, in __init__
    self.bag = bagit.Bag(unicode(self.path))
  File "/usr/local/lib/python2.7/dist-packages/spreads/vendor/bagit.py", line 113, in __init__
    self._read_bag()
  File "/usr/local/lib/python2.7/dist-packages/spreads/vendor/bagit.py", line 296, in _read_bag
    version = fp.readlines()[0].split(':')[1].strip()
IndexError: list index out of range
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/spreadsplug/web/endpoints.py", line 522, in list_workflows
    workflows = Workflow.find_all(app.config['base_path'])
  File "/usr/local/lib/python2.7/dist-packages/spreads/workflow.py", line 355, in find_all
    workflow = cls(candidate)
  File "/usr/local/lib/python2.7/dist-packages/spreads/workflow.py", line 426, in __init__
    self.bag = bagit.Bag(unicode(self.path))
  File "/usr/local/lib/python2.7/dist-packages/spreads/vendor/bagit.py", line 113, in __init__
    self._read_bag()
  File "/usr/local/lib/python2.7/dist-packages/spreads/vendor/bagit.py", line 296, in _read_bag
    version = fp.readlines()[0].split(':')[1].strip()
IndexError: list index out of range
```

**Comment by markvdb** [comment]
Full log, including some extra cruft...
<pre>
{
  "messages": [
    {
      "level": "ERROR", 
      "message": "500 POST /api/workflow/13b849a1-d0cb-4826-9aa1-3110cd526cd9/capture (192.168.1.45) 88.08ms", 
      "origin": "tornado.access", 
      "time": 1424255412.3, 
      "traceback": null
    }, 
    {
      "level": "ERROR", 
      "message": "Uncaught exception POST /api/workflow/13b849a1-d0cb-4826-9aa1-3110cd526cd9/capture (192.168.1.45)\nHTTPServerRequest(protocol='http', host='spreadpi.zyxel.com', method='POST', uri='/api/workflow/13b849a1-d0cb-4826-9aa1-3110cd526cd9/capture', version='HTTP/1.1', remote_ip='192.168.1.45', headers={'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Host': 'spreadpi.zyxel.com', 'Accept': '*/*', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:31.0) Gecko/20100101 Firefox/31.0 Iceweasel/31.4.0', 'Connection': 'keep-alive', 'X-Requested-With': 'XMLHttpRequest', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache', 'Referer': 'http://spreadpi.zyxel.com/workflow/test/capture'})", 
      "origin": "tornado.application", 
      "time": 1424255367.45, 
      "traceback": "Traceback (most recent call last):\n  File \"/usr/local/lib/python2.7/dist-packages/tornado/web.py\", line 1323, in _execute\n    result = self.prepare()\n  File \"/usr/local/lib/python2.7/dist-packages/tornado/web.py\", line 2517, in prepare\n    self.fallback(self.request)\n  File \"/usr/local/lib/python2.7/dist-packages/tornado/wsgi.py\", line 277, in __call__\n    WSGIContainer.environ(request), start_response)\n  File \"/usr/lib/python2.7/dist-packages/flask/app.py\", line 1836, in __call__\n    return self.wsgi_app(environ, start_response)\n  File \"/usr/lib/python2.7/dist-packages/flask/app.py\", line 1812, in wsgi_app\n    ctx = self.request_context(environ)\n  File \"/usr/lib/python2.7/dist-packages/flask/app.py\", line 1773, in request_context\n    return RequestContext(self, environ)\n  File \"/usr/lib/python2.7/dist-packages/flask/ctx.py\", line 247, in __init__\n    self.match_request()\n  File \"/usr/lib/python2.7/dist-packages/flask/ctx.py\", line 286, in match_request\n    self.url_adapter.match(return_rule=True)\n  File \"/usr/lib/python2.7/dist-packages/werkzeug/routing.py\", line 1381, in match\n    rv = rule.match(path)\n  File \"/usr/lib/python2.7/dist-packages/werkzeug/routing.py\", line 689, in match\n    value = self._converters[name].to_python(value)\n  File \"/usr/local/lib/python2.7/dist-packages/spreadsplug/web/util.py\", line 127, in to_python\n    workflow = Workflow.find_by_id(app.config['base_path'], value)\n  File \"/usr/local/lib/python2.7/dist-packages/spreads/workflow.py\", line 373, in find_by_id\n    return cls.find_all(location, key='id')[id]\n  File \"/usr/local/lib/python2.7/dist-packages/spreads/workflow.py\", line 355, in find_all\n    workflow = cls(candidate)\n  File \"/usr/local/lib/python2.7/dist-packages/spreads/workflow.py\", line 426, in __init__\n    self.bag = bagit.Bag(unicode(self.path))\n  File \"/usr/local/lib/python2.7/dist-packages/spreads/vendor/bagit.py\", line 113, in __init__\n    self._read_bag()\n  File \"/usr/local/lib/python2.7/dist-packages/spreads/vendor/bagit.py\", line 296, in _read_bag\n    version = fp.readlines()[0].split(':')[1].strip()\nIndexError: list index out of range\n"
    }, 
    {
      "level": "DEBUG", 
      "message": "Initializing workflow /home/spreads/scans/castors-and-wheels", 
      "origin": "Workflow", 
      "time": 1424255350.164, 
      "traceback": null
    }, 
    {
      "level": "DEBUG", 
      "message": "Cache missed, instantiating workflow from /home/spreads/scans/castors-and-wheels.", 
      "origin": "root", 
      "time": 1424255334.908, 
      "traceback": null
    }, 
    {
      "level": "ERROR", 
      "message": "500 POST /api/workflow/13b849a1-d0cb-4826-9aa1-3110cd526cd9/prepare_capture (192.168.1.45) 126.66ms", 
      "origin": "tornado.access", 
      "time": 1424255059.628, 
      "traceback": null
    }, 
    {
      "level": "ERROR", 
      "message": "Uncaught exception POST /api/workflow/13b849a1-d0cb-4826-9aa1-3110cd526cd9/prepare_capture (192.168.1.45)\nHTTPServerRequest(protocol='http', host='spreadpi.zyxel.com', method='POST', uri='/api/workflow/13b849a1-d0cb-4826-9aa1-3110cd526cd9/prepare_capture', version='HTTP/1.1', remote_ip='192.168.1.45', headers={'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Host': 'spreadpi.zyxel.com', 'Accept': '*/*', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:31.0) Gecko/20100101 Firefox/31.0 Iceweasel/31.4.0', 'Connection': 'keep-alive', 'X-Requested-With': 'XMLHttpRequest', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache', 'Referer': 'http://spreadpi.zyxel.com/workflow/test/capture'})", 
      "origin": "tornado.application", 
      "time": 1424254975.79, 
      "traceback": "Traceback (most recent call last):\n  File \"/usr/local/lib/python2.7/dist-packages/tornado/web.py\", line 1323, in _execute\n    result = self.prepare()\n  File \"/usr/local/lib/python2.7/dist-packages/tornado/web.py\", line 2517, in prepare\n    self.fallback(self.request)\n  File \"/usr/local/lib/python2.7/dist-packages/tornado/wsgi.py\", line 277, in __call__\n    WSGIContainer.environ(request), start_response)\n  File \"/usr/lib/python2.7/dist-packages/flask/app.py\", line 1836, in __call__\n    return self.wsgi_app(environ, start_response)\n  File \"/usr/lib/python2.7/dist-packages/flask/app.py\", line 1812, in wsgi_app\n    ctx = self.request_context(environ)\n  File \"/usr/lib/python2.7/dist-packages/flask/app.py\", line 1773, in request_context\n    return RequestContext(self, environ)\n  File \"/usr/lib/python2.7/dist-packages/flask/ctx.py\", line 247, in __init__\n    self.match_request()\n  File \"/usr/lib/python2.7/dist-packages/flask/ctx.py\", line 286, in match_request\n    self.url_adapter.match(return_rule=True)\n  File \"/usr/lib/python2.7/dist-packages/werkzeug/routing.py\", line 1381, in match\n    rv = rule.match(path)\n  File \"/usr/lib/python2.7/dist-packages/werkzeug/routing.py\", line 689, in match\n    value = self._converters[name].to_python(value)\n  File \"/usr/local/lib/python2.7/dist-packages/spreadsplug/web/util.py\", line 127, in to_python\n    workflow = Workflow.find_by_id(app.config['base_path'], value)\n  File \"/usr/local/lib/python2.7/dist-packages/spreads/workflow.py\", line 373, in find_by_id\n    return cls.find_all(location, key='id')[id]\n  File \"/usr/local/lib/python2.7/dist-packages/spreads/workflow.py\", line 355, in find_all\n    workflow = cls(candidate)\n  File \"/usr/local/lib/python2.7/dist-packages/spreads/workflow.py\", line 426, in __init__\n    self.bag = bagit.Bag(unicode(self.path))\n  File \"/usr/local/lib/python2.7/dist-packages/spreads/vendor/bagit.py\", line 113, in __init__\n    self._read_bag()\n  File \"/usr/local/lib/python2.7/dist-packages/spreads/vendor/bagit.py\", line 296, in _read_bag\n    version = fp.readlines()[0].split(':')[1].strip()\nIndexError: list index out of range\n"
    }, 
    {
      "level": "DEBUG", 
      "message": "Initializing workflow /home/spreads/scans/castors-and-wheels", 
      "origin": "Workflow", 
      "time": 1424254957.433, 
      "traceback": null
    }, 
    {
      "level": "DEBUG", 
      "message": "Cache missed, instantiating workflow from /home/spreads/scans/castors-and-wheels.", 
      "origin": "root", 
      "time": 1424254943.832, 
      "traceback": null
    }, 
    {
      "level": "DEBUG", 
      "message": "Found HID device: <hidapi.Device object at 0x1ddb810>", 
      "origin": "spreadsplug.hidtrigger", 
      "time": 1424254801.978, 
      "traceback": null
    }, 
    {
      "level": "DEBUG", 
      "message": "Found HID device: <hidapi.Device object at 0x1ddb690>", 
      "origin": "spreadsplug.hidtrigger", 
      "time": 1424254764.925, 
      "traceback": null
    }, 
    {
      "level": "DEBUG", 
      "message": "Initializing HidTrigger plugin", 
      "origin": "spreadsplug.hidtrigger", 
      "time": 1424255578.46, 
      "traceback": null
    }, 
    {
      "level": "DEBUG", 
      "message": "Initializing workflow /home/spreads/scans/test", 
      "origin": "Workflow", 
      "time": 1424255474.066, 
      "traceback": null
    }, 
    {
      "level": "ERROR", 
      "message": "500 GET /api/workflow (192.168.1.45) 110.58ms", 
      "origin": "tornado.access", 
      "time": 1424254755.382, 
      "traceback": null
    }, 
    {
      "level": "ERROR", 
      "message": "list index out of range", 
      "origin": "spreadsplug.web", 
      "time": 1424254684.195, 
      "traceback": "Traceback (most recent call last):\n  File \"/usr/lib/python2.7/dist-packages/flask/app.py\", line 1475, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/usr/lib/python2.7/dist-packages/flask/app.py\", line 1461, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"/usr/local/lib/python2.7/dist-packages/spreadsplug/web/endpoints.py\", line 522, in list_workflows\n    workflows = Workflow.find_all(app.config['base_path'])\n  File \"/usr/local/lib/python2.7/dist-packages/spreads/workflow.py\", line 355, in find_all\n    workflow = cls(candidate)\n  File \"/usr/local/lib/python2.7/dist-packages/spreads/workflow.py\", line 426, in __init__\n    self.bag = bagit.Bag(unicode(self.path))\n  File \"/usr/local/lib/python2.7/dist-packages/spreads/vendor/bagit.py\", line 113, in __init__\n    self._read_bag()\n  File \"/usr/local/lib/python2.7/dist-packages/spreads/vendor/bagit.py\", line 296, in _read_bag\n    version = fp.readlines()[0].split(':')[1].strip()\nIndexError: list index out of range\n"
    }, 
    {
      "level": "DEBUG", 
      "message": "Initializing workflow /home/spreads/scans/castors-and-wheels", 
      "origin": "Workflow", 
      "time": 1424254665.739, 
      "traceback": null
    }, 
    {
      "level": "DEBUG", 
      "message": "Cache missed, instantiating workflow from /home/spreads/scans/castors-and-wheels.", 
      "origin": "root", 
      "time": 1424254655.624, 
      "traceback": null
    }, 
    {
      "level": "INFO", 
      "message": "Starting periodic task scheduler thread", 
      "origin": "huey.consumer.ConsumerThread", 
      "time": 1424255098.389, 
      "traceback": null
    }, 
    {
      "level": "INFO", 
      "message": "Starting worker threads", 
      "origin": "huey.consumer.ConsumerThread", 
      "time": 1424255080.551, 
      "traceback": null
    }, 
    {
      "level": "INFO", 
      "message": "Starting scheduler thread", 
      "origin": "huey.consumer.ConsumerThread", 
      "time": 1424255072.566, 
      "traceback": null
    }, 
    {
      "level": "INFO", 
      "message": "Huey consumer initialized with following commands\n+ process_workflow\n+ upload_workflow\n+ transfer_to_stick\n+ output_workflow", 
      "origin": "huey.consumer.ConsumerThread", 
      "time": 1424255061.012, 
      "traceback": null
    }, 
    {
      "level": "INFO", 
      "message": "Setting signal handler", 
      "origin": "huey.consumer.ConsumerThread", 
      "time": 1424255054.172, 
      "traceback": null
    }, 
    {
      "level": "INFO", 
      "message": "1 worker threads", 
      "origin": "huey.consumer.ConsumerThread", 
      "time": 1424255047.283, 
      "traceback": null
    }, 
    {
      "level": "DEBUG", 
      "message": "Finding devices for driver \"CHDKCameraDevice\"", 
      "origin": "spreads.plugin", 
      "time": 1424255495.418, 
      "traceback": null
    }
  ], 
  "total_num": 23
}
</pre>

**Comment by markvdb** [comment]
More info about bagit, as requested:
<pre>
spreads@spreadpi ~ $ ls
scans
spreads@spreadpi ~ $ ls scans/
castors-and-wheels  test
spreads@spreadpi ~ $ ls scans/test/
bag-info.txt  bagit.txt  config.yml  data  dcmeta.txt  manifest-md5.txt  tagmanifest-md5.txt
spreads@spreadpi ~ $ ls scans/castors-and-wheels/
bag-info.txt  bagit.txt  config.yml  data  dcmeta.txt  manifest-md5.txt  tagmanifest-md5.txt
spreads@spreadpi ~ $ cat scans/test/bag
bag-info.txt  bagit.txt     
spreads@spreadpi ~ $ cat scans/test/bagit.txt 
BagIt-Version: 0.97
Tag-File-Character-Encoding: UTF-8
spreads@spreadpi ~ $ cat scans/castors-and-wheels/bagit.txt 
spreads@spreadpi ~ $ 
</pre>

**Comment by adongy** [comment]
Empty bagit.txt suggests it was not created properly.
I don't know how it was created without anything in it, as https://github.com/DIYBookScanner/spreads/blob/master/spreads/vendor/bagit.py#L277 is the only place where spreads write into the file, and it should fail earlier if it didn't manage to write (with an IOError)

Copying the test one to the castors-and-wheels should fix the issue, but the real problem lies elsewhere...

**Comment by markvdb** [comment]
This probably was an sd card issue. There were some other issues that made me suspect that too... Closing as I can't reproduce it with a brand new sd card from the same series.
