### ISSUE TITLE
PTPError: I/O error (ptp_code: 767),

### ISSUE THREAD

**Issue by ca5tl3hill** [DIYBookScanner/spreads#166]
I'm getting PTP 767 error, my setup is:
-latest nightly build SpreadPi (20150206)
-Raspberry Pi B+
-two Canon A2500 with CHDK

When starting a new workflow one of the cameras crashes.

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/spreadsplug/web/endpoints.py", line 327, in view_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/spreadsplug/web/endpoints.py", line 929, in prepare_capture
    workflow.prepare_capture()
  File "/usr/local/lib/python2.7/dist-packages/spreads/workflow.py", line 868, in prepare_capture
    util.check_futures_exceptions(futures)
  File "/usr/local/lib/python2.7/dist-packages/spreads/util.py", line 119, in check_futures_exceptions
    raise next(x for x in futures if x.exception()).exception()
PTPError: I/O error (ptp_code: 767)

```

**Comment by adongy** [comment]
Can you try with a different USB cable?

ca5tl3hill wrote:
> I'm getting PTP 767 error, my setup is:
> -latest nightly build SpreadPi (20150206)
> -Raspberry Pi B+
> -two Canon A2500 with CHDK
>
> When starting a new workflow one of the cameras crashes.
>
> |Traceback (most recent call last):
>    File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
>      rv = self.dispatch_request()
>    File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
>      return self.view_functions[rule.endpoint](**req.view_args)
>    File "/usr/local/lib/python2.7/dist-packages/spreadsplug/web/endpoints.py", line 327, in view_func
>      return func(*args, **kwargs)
>    File "/usr/local/lib/python2.7/dist-packages/spreadsplug/web/endpoints.py", line 929, in prepare_capture
>      workflow.prepare_capture()
>    File "/usr/local/lib/python2.7/dist-packages/spreads/workflow.py", line 868, in prepare_capture
>      util.check_future
s_exceptions(futures)

**Comment by jbaiter** [comment]
Try to fiddle around with the usual list of suspects:

[ ] Try different USB cables
[ ] Try to put the two cameras on different USB busses (or at least different USB ports on the device directly, no hub in between)
[ ] Make sure you run the latest CHDK 1.3 release

**Comment by ca5tl3hill** [comment]
I changed nearly everything

-USB cables (camera)
-SD cards (camera)
-different USB ports (direct connection)
-power supply (PI)
-MicroSD card (PI)

I flashed SpreadPi image several times. Sometimes webgui did not recognize the cameras at all, although I could list and connect the cameras via SSH + CHDKPTP.

Finally I tested an earlier version of SpreadPi (spreadpi-20141106.img.7z). Now webgui is working as it should.

I have to test the latest build again if the problem renew. I noticed that one of the cameras batteries is in bad condition. That would be a cause of problem also.

**Comment by johnelle** [comment]
I am running the latest SpreadPi version on B+ hardware using two Canon
A1400s and its seems to be fine.  Did a few sessions on Sunday scanning a
small number of pages but I didn't run across any bugs.

On Tue, Feb 24, 2015 at 6:03 AM, ca5tl3hill <notifications@github.com>
wrote:

> I changed nearly everything
>
> -USB cables (camera)
> -SD cards (camera)
> -different USB ports (direct connection)
> -power supply (PI)
> -MicroSD card (PI)
>
> I flashed SpreadPi image several times. Sometimes webgui did not recognize
> the cameras at all, although I could list and connect the cameras via SSH +
> CHDKPTP.
>
> Finally I tested an earlier version of SpreadPi
> (spreadpi-20141106.img.7z). Now webgui is working as it should.
>
> I have to test the latest build again if the problem renew. I noticed that
> one of the cameras batteries is in bad condition. That would be a cause of
> problem also.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DIYBookScanner/spreads/issues/166#issuecomment-75737301>
> .
>



-- 
John Ellenberger
Groton, MA

**Comment by markvdb** [comment]
Ca5tl3hill, can you check if this issue still appears with the latest spreadpi version? Otherwise, it makes more sense for me to close this issue within the next month, as it's impossible to reproduce without your exact hardware and software setup...

**Comment by NickBarreto** [comment]
I'm having a similar issue. 

Pretty much the same setup, though I don't know which build exactly I am on for spreadpi. It may be that I need to update, will have to try that and see. 

I was having an issue where a badly saved .jpg image, presumably from the faulty camera was causing a segfault and bringing everything to a crashing halt. I managed to solve that by using ssh to remove the offending images (as well are references to them in the meta files and checksums). After doing this, things appears to have returned to normal, and I was able to capture a few more images. But now every time I try to capture, I get the same I/O error, even though both cameras appear to be connected and do show the IP address on their screens.

>spreadsplug.web: I/O error (ptp_code: 767)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/spreadsplug/web/endpoints.py", line 327, in view_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/spreadsplug/web/endpoints.py", line 929, in prepare_capture
    workflow.prepare_capture()
  File "/usr/local/lib/python2.7/dist-packages/spreads/workflow.py", line 868, in prepare_capture
    util.check_futures_exceptions(futures)
  File "/usr/local/lib/python2.7/dist-packages/spreads/util.py", line 119, in check_futures_exceptions
    raise next(x for x in futures if x.exception()).exception()
PTPError: I/O error (ptp_code: 767)
tornado.access: 500 POST /api/workflow/0cc50e36-5606-47cd-8fa7-e6fae528b543/prepare_capture (192.168.1.99) 7251.97ms

If I were to update to the latest build, what would be the best way of going about that? Should I just run apt-get update + apt-get upgrade?

**Comment by jbaiter** [comment]
Since it looks like you're on a pretty old version, I recommend backing up your scans and just re-flashing the SD card. There are a bunch of rather nasty new dependencies (which require compiling some binary stuff) that you probably don't want to do on the Pi itself.

**Comment by ca5tl3hill** [comment]
I bought two power supplys for Canon A1400s and the issue disappeared. I have also flashed the latest SpreadPi and it works fine.
