### ISSUE TITLE
You need to specify a value for `driver`.

### ISSUE THREAD

**Issue by boredland** [DIYBookScanner/spreads#167]
Spreads can't be started without a driver (selected 0-none):
```
There is a problem with your configuration file(s):
You need to specify a value for `driver`.
Either run `spread [gui]configure` or edit the configuration file.
```

**Comment by knjigor** [comment]
Yes, before you can run spread you have to run spread configure or spread guiconfigure with cameras attached

**Comment by boredland** [comment]
But for processing-servers that doesn't come in very handy, does it?

2015-02-23 22:22 GMT+01:00 knjigor <notifications@github.com>:

**Comment by knjigor** [comment]
I think that then you can select ```dummy driver``` but any way you have to select "components" like autorotate, pdf, teserac, scantailor without setting cameras.

**Comment by knjigor** [comment]
I will post my ```config.yaml``` tomorrow.

**Comment by boredland** [comment]
Hi there. From my point we could close this. Perhaps we could simply delete the 'none' option - at least I dont see the point of it.
