### ISSUE TITLE
libturbojpeg.a on arm

### ISSUE THREAD

**Issue by boredland** [DIYBookScanner/spreads#169]
This occurs, only the web-plugin enabled, on armhf:

```
(.spreads)firefly@firefly:~/spreads-deploy$ spread web
/usr/bin/ld: /usr/lib/gcc/arm-linux-gnueabihf/4.8/../../../arm-linux-gnueabihf/libturbojpeg.a(libturbojpeg_la-turbojpeg.o): relocation R_ARM_THM_MOVW_ABS_NC against `a local symbol' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/arm-linux-gnueabihf/4.8/../../../arm-linux-gnueabihf/libturbojpeg.a: error adding symbols: Bad value
```
I think that's the cause for some install manuals for adding a symbolic link, but I don't know exactly why it comes up. On the other hand: the spreads webclient is up and running with this error message.

**Comment by jbaiter** [comment]
Well, that looks a lot like a bug in your distribution's libturbojpeg packages, have you filed a bug with them?

**Comment by boredland** [comment]
no, I created a symlink "sudo ln -s /usr/lib/arm-linux-gnueabihf/libturbojpeg.so.0.0.0 /usr/lib/arm-linux-gnueabihf/libturbojpeg.so". That solved it.
