### ISSUE TITLE
Post-process plugin ordering?

### ISSUE THREAD

**Issue by gareth8118** [DIYBookScanner/spreads#171]
Is there a way to express dependencies in plugins or the order they are to run in? Seems to be alphabetical just now but I wasn't sure.

To support single camera use, there is a case for running some of the post-processing before autorotate and some after - http://www.diybookscanner.org/forum/viewtopic.php?f=35&t=3148&p=18697#p18697

My alternative is to replicate the autorotate function inside a monolithic plugin to support single camera use, but I don't think that's the optimal solution.

**Comment by adongy** [comment]
I think the config file will iterate the list in order, so you could list them as is and it will run in the order you specified.

**Comment by gareth8118** [comment]
Sorry, I just spotted in setup-other.rst:

> configure the order in which your postprocessing plugins should be invoked. Think of it as a pipelining system, where each of the plugin gets fed the output of its predecessor.

Please close this issue.
