### ISSUE TITLE
"ValueError: too many values to unpack"

### ISSUE THREAD

**Issue by boredland** [DIYBookScanner/spreads#181]
Fresh install (ubuntu 14.04) - still no luck even setting up the devices.
```
spreads.plugin: Finding devices for driver "CHDKCameraDevice"
spreads encountered an error:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/spreads/main.py", line 321, in main
    run()
  File "/usr/local/lib/python2.7/dist-packages/spreads/main.py", line 308, in run
    args.subcommand(config)
  File "/usr/local/lib/python2.7/dist-packages/spreads/cli.py", line 232, in configure
    _set_device_target_page(config, target_page)
  File "/usr/local/lib/python2.7/dist-packages/spreads/cli.py", line 183, in _set_device_target_page
    devs[0].set_target_page(target_page)
  File "/usr/local/lib/python2.7/dist-packages/spreadsplug/dev/chdkcamera.py", line 166, in set_target_page
    self._device.upload_file(tmp_handle[1], "OWN.TXT")
  File "/usr/local/lib/python2.7/dist-packages/chdkptp/device.py", line 222, in upload_file
    status, error = self._lua.call("con:stat", remote_path)
ValueError: too many values to unpack
```
The camera is available for the group "plugdev":
crw-rw-r--+ 1 root plugdev 189, 1054 Mär 23 22:25 /dev/bus/usb/009/031
The user is member of plugdev:
adm cdrom sudo dip plugdev lpadmin sambashare

I think I'm out for spreads, unfortunately. I can't even get a regular install on a regular computer to just shoot and do post-processing - not to speak of the spreadpi - processing-server solution.

**Comment by adongy** [comment]
Could you use something like
http://code.activestate.com/recipes/65287-automatically-start-the-debugger-on-an-exception/

then paste what the last line returns?
(self._lua...)

On March 23, 2015 10:30:55 PM CET, boredland <notifications@github.com> wrote:
>Fresh install (ubuntu 14.04) - still no luck even setting up the
>devices.
>```
>spreads.plugin: Finding devices for driver "CHDKCameraDevice"
>spreads encountered an error:
>Traceback (most recent call last):
>File "/usr/local/lib/python2.7/dist-packages/spreads/main.py", line
>321, in main
>    run()
>File "/usr/local/lib/python2.7/dist-packages/spreads/main.py", line
>308, in run
>    args.subcommand(config)
>File "/usr/local/lib/python2.7/dist-packages/spreads/cli.py", line 232,
>in configure
>    _set_device_target_page(config, target_page)
>File "/usr/local/lib/python2.7/dist-packages/spreads/cli.py", line 183,
>in _set_device_target_page
>    devs[0].set_target_page(target_page)
>File
>"/usr/local/lib/python2.7/dist-packages/spreadsplug/dev/chdkcamera.py",
>line 166, in set_target_page
>    self._device.upload_file(tmp_handle[1], "OWN.TXT")
>File "/usr/local/lib/python2.7/dist-packages/chdkptp/device.py", line
>222, in upload_file
>    status, error = self._lua.call("con:stat", remote_path)
>ValueError: too many values to unpack
>```
>The camera is available for the group "plugdev":
>crw-rw-r--+ 1 root plugdev 189, 1054 Mär 23 22:25 /dev/bus/usb/009/031
>The user is member of plugdev:
>adm cdrom sudo dip plugdev lpadmin sambashare
>
>I think I'm out for spreads, unfortunately. I can't even get a regular
>install on a regular computer to just shoot and do post-processing -
>not to speak of the spreadpi - processing-server solution.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/DIYBookScanner/spreads/issues/181

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by boredland** [comment]
Hm. I don't understand. Where should I insert that?
What I don't understand either: Is nobody running spreads on a regular debian/ubuntu setup? Could it be so hard?

**Comment by adongy** [comment]
Edit /usr/local/lib/python2.7/dist-packages/spreads/main.py
Right before the # Deinitialize (should be at the end of the file), add:
```
import pdb
pdb.pm()
```

with the same indenting as the print_error line that should be right above.

Now run spreads again, make it crash. This time instead of exiting, it should give you a console.
Type in `self._lua.call("con:stat", remote_path)` and paste the result

**Comment by boredland** [comment]
I think I did it wrong:
```
Traceback (most recent call last):
  File "/usr/local/bin/spread", line 9, in <module>
    load_entry_point('spreads==0.5git20150302.3ede', 'console_scripts',
'spread')()
  File "/usr/local/lib/python2.7/dist-packages/spreads/main.py", line 346,
in main
    pdb.pm()
  File "/usr/lib/python2.7/pdb.py", line 1270, in pm
    post_mortem(sys.last_traceback)
AttributeError: 'module' object has no attribute 'last_traceback'
```
No console...
A snippet from the main.py:
```
print_error("spreads encountered an error:")
        print_error("".join(traceback.format_exception(typ, val, tb)))
        import pdb
        pdb.pm()
    # Deinitialize color support
    colorama.deinit()

```
2015-03-23 23:04 GMT+01:00 Anthony Dong <notifications@github.com>:

> pdb.pm()
>
>

**Comment by adongy** [comment]
Sorry it was my bad, it's been forever since I last used pdb...
The line pdb.pm() should be pdb.post_mortem()
And to print the result of the function, you should do `pp self._lua.call("con:stat", remote_path)`

**Comment by adongy** [comment]
Did you manage to debug it ?

**Comment by boredland** [comment]
No did not try it anymore - tomorrow maybe.

2015-03-26 15:59 GMT+01:00 Anthony Dong <notifications@github.com>:

**Comment by markvdb** [comment]
I see no reaction. Is this issue solved? Or can we close it?

**Comment by jbaiter** [comment]
This should be fixed now, please comment if this is not the case and I'll reopen.
