### ISSUE TITLE
LuaError: "error loading module 'propcase' from file 'A/CHDK/LUALIB/propcase.lua'

### ISSUE THREAD

**Issue by ktverdun** [DIYBookScanner/spreads#186]
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/spreadsplug/web/endpoints.py", line 327, in view_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/spreadsplug/web/endpoints.py", line 929, in prepare_capture
    workflow.prepare_capture()
  File "/usr/local/lib/python2.7/dist-packages/spreads/workflow.py", line 868, in prepare_capture
    util.check_futures_exceptions(futures)
  File "/usr/local/lib/python2.7/dist-packages/spreads/util.py", line 119, in check_futures_exceptions
    raise next(x for x in futures if x.exception()).exception()
LuaError: {'msg': "error loading module 'propcase' from file 'A/CHDK/LUALIB/propcase.lua':\n\tcannot fopen A/CHDK/LUALIB/propcase.lua", 'etype': 'exec_runtime', 'traceback': '\nstack traceback:\n\t...on2.7/dist-packages/chdkptp/vendor/chdkptp/lua/chdku.lua:966: in function <...on2.7/dist-packages/chdkptp/vendor/chdkptp/lua/chdku.lua:855>\n\t(...tail calls...)\n\t[string "<python>"]:4: in function <[string "<python>"]:1>\n\t[C]: in function \'pcall\'\n\t[string "<python>"]:1: in main chunk'}

```

**Comment by adongy** [comment]
You likely didn't put the full CHDK package in your camera.
There should be a CHDK folder at the root of it, with the lua plugins.

**Comment by markvdb** [comment]
Almost certain that is the case too. Jbaiter, do you want me to help triage bugs here and there? Maybe it would be useful if I could close ones like this for you? I seem not to have sufficient rights for that right now...

**Comment by jbaiter** [comment]
That would be great, mark. I just added you to the team, you should be able to close/edit issues now :-)

**Comment by ktverdun2** [comment]
The cards were set up with STICK to load chdk on them.  The /propcase.lua was on both SD cards, which threw me off for a bit.

I re-formatted the SD cards and reloaded chdk on both cards and that got me to a point were I could capture a few test pictures from the cameras.  However, when I go to download them from the web gui, spreadpi either crashes (and I need to unplug the pi) or the zip file seems to contain corrupt jpg files that cannot be opened or extracted from the zip file.  

I'm using the latest spreadpi image.

**Comment by adongy** [comment]
Can you provide logs ?
Try running spreads with `--verbose capture`, the logs should be in `~/.config/spreads/spreads.log`.

**Comment by ktverdun2** [comment]
I can't get back to the logs.  Once the issue happens, the pi will not clean start up again.  I see something like the following in when I look at the monitor attached to the PI (both at the time of the issue and when I unplug and restart).

![img_0366](https://cloud.githubusercontent.com/assets/12122939/7339359/4ce3b8d6-ec31-11e4-9e52-e4a1365adf8f.JPG)

The only way I can get back in is if I reformat the PI's micro SD card, reload the image and start the process all over again.

**Comment by markvdb** [comment]
This smells like pi SD card corruption to me. SD cards are fairly
sensitive...

You would do best to test with a different new high quality A brand card
from a well known source.

2015-04-26 23:31 GMT+02:00 ktverdun2 <notifications@github.com>:

> I can't get back to the logs. Once the issue happens, the pi will not
> clean start up again. I see something like the following in when I look at
> the monitor attached to the PI (both at the time of the issue and when I
> unplug and restart).
>
> [image: img_0366]
> <https://cloud.githubusercontent.com/assets/12122939/7339359/4ce3b8d6-ec31-11e4-9e52-e4a1365adf8f.JPG>
>
> The only way I can get back in is if I reformat the PI's micro SD card,
> reload the image and start the process all over again.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DIYBookScanner/spreads/issues/186#issuecomment-96436984>
> .
>



-- 
Mark Van den Borre
Hogestraat 16
3000 Leuven, België
+32 486 961726
