### ISSUE TITLE
spreads repo key

### ISSUE THREAD

**Issue by lupa18** [DIYBookScanner/spreads#211]
hello, we are trying to upgrade spreads but appears this error:

W: GPG error: http://apt.diybookscanner.org wheezy InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 8D06155817A93300

what could be wrong here=

**Comment by markvdb** [comment]
The apt repository is quite a bit behind schedule (spreads from 20140717!). I would really not use that right now. Either the spreads buildbot ( http://buildbot.diybookscanner.eu ) or straight from source is recommended right now. This is not ideal. I hope to be able to spend some time on getting spreads into Debian.

If you would want to use the debian packages for some (historical?) reason, you would have to either:
* trust the packages from that repository without signing (bad security practice)
* or add the key for this repo to your keyring (I checked the popular MIT keyserver, but no cigar; need info from Johannes)
* or ignore the key alltogether (worst security practice, --allow-unauthenticated option to apt-get )

More background:
* https://www.gnupg.org/gph/en/manual/x457.html
