### ISSUE TITLE
Error tuple index out of range

### ISSUE THREAD

**Issue by lupa18** [DIYBookScanner/spreads#212]
We are trying to get working spreads but this error appears:

![error-spreads](https://cloud.githubusercontent.com/assets/463429/9319853/2464b614-4521-11e5-8c47-b149a2dd2296.png)

Spreads version: spreadpi-latest.img.7z (spreadpi-20150527.img.7z)
Camera: PowerShot A2200
CHDK Version: 1.3

**Comment by markvdb** [comment]
Known, solved issue. See #190 . Please use a more recent version of spreads and -most importantly- its supporting libraries. The buildbot currently does not generate them for some reason. I'll try to investigate. In the mean time, you might do a manual install to a pi 1 b/b+(take hints from the spreads manual and spreadpi build scripts). For the pi 2b, duerig has generated recent images in a different way at http://tenrec.builders/pi/archivist-2m.zip .

**Comment by lupa18** [comment]
Ok, I saw #190 but there is too much options for the update and it not appear to be solved. How can update for pi 1 b+ ?

**Comment by lupa18** [comment]
Sorry, could you please update your documentation?

**Comment by lupa18** [comment]
We make all installation again, but we are getting the same error. This time we use CLI: http://pastebin.com/cCSHmQQw
