### ISSUE TITLE
Can't zoom Canon SX170 Camera

### ISSUE THREAD

**Issue by barnaclebarnes** [DIYBookScanner/spreads#213]
I'm new to Spreads and have just got my set up working with an Archivist kit and running 2 [Canon SX170](https://www.canon.co.nz/en/Personal/Products/Cameras-and-Accessories/Digital-Cameras/PowerShot-SX170-IS) cameras. I've managed to make my first scans and tested that this works and now I'm trying to tweak some settings. 

I want to zoom the cameras in quite a bit but no matter what I set the zoom level to it doesn't seem to do anything. So two questions:

1. How do I tell how many zoom levels my camera supports? I tried `chdkptp` but I can't seem to work out how to run or print out the results of [get_zoom_steps()](http://chdk.wikia.com/wiki/Script_commands#get_zoom_steps).
2. How can I test to see whether this should working or where things are going wrong.

**Comment by nafraf** [comment]
Using chdkptp:
`con> =return get_zoom_steps()`
From CHDK source code, SX170 has 127 zoom steps.

**Comment by barnaclebarnes** [comment]
I was using either too smaller numbers and not seeing anything or too bigger numbers and getting an erro. all good now.
