### ISSUE TITLE
Spread configure error

### ISSUE THREAD

**Issue by lupa18** [DIYBookScanner/spreads#215]
We followed all steps here: https://github.com/DIYBookScanner/spreads#getting-started

In configuration step, we choose all options excluding GUI and got this error: http://pastebin.com/xaZ80B5x

**Comment by markvdb** [comment]
Updated docs fix this (commit a94bc08 ) . Read the error output before reporting a bug please.

You just needed djvubind on your path...

**Comment by lupa18** [comment]
Yes, but remember we are not necessary programmers and general couldn't understand those kinds of outputs. 

I found error but then get new ones, that can be fixed with new installations:
sudo apt-get install -y djvubind scantailor

Finnally, one more dependence could not be installed: pdfbeads
It depends on jbig2enc and this package depends on liblept3 that has no candidate. 
Is this package important?

**Comment by lupa18** [comment]
Then installed ruby, trying to install pdfbean gem and got this error:

spreads@spreadpi ~ $ sudo gem install pdfbeads                                                                 
[sudo] password for spreads: 
Fetching: rmagick-2.15.4.gem (100%)
Building native extensions.  This could take a while...
Fetching: mini_portile-0.6.2.gem (100%)
Fetching: nokogiri-1.6.6.2.gem (100%)
ERROR:  Error installing pdfbeads:
        nokogiri requires Ruby version >= 1.9.2.
